package com.marks.edms.util;

public class DocumentDefinition {
    public static void main(String[] args) {
//        String str = "dd.text_Field01 AS 'Location', dd.text_Field02 AS 'Industry Client Partner', dd.text_Field03 AS 'Customer Name', dd.text_Field04 AS 'Project Description', dd.text_Field05 AS 'Industry', dd.text_Field06 AS 'Currency', dd.num_Field01 AS 'TCV before VAT', dd.num_Field02 AS 'TCV before VAT(HKD)', dd.date_Field01 AS 'Expected Contract Sign Date', dd.text_Field07 AS 'Account Manager', dd.text_Field08 AS 'Solution Manager', dd.text_Field09 AS 'Project Nature', dd.num_Field03 AS 'Total Direct Variable Cost', dd.num_Field04 AS 'Total Indirect Cost', dd.text_Field10 AS 'Year of New Sales Booked Revenue', dd.num_Field05 AS 'New Sales Booked Revenue', dd.num_Field06 AS 'EBITDA : ', dd.num_Field07 AS 'EBIDTA Margin (in %) ', dd.text_Field11 AS 'Opportunity ID', dd.text_Field12 AS 'Inculding Type', dd.num_Field08 AS 'EBIDTA Guideline', dd.num_Field09 AS 'Total No. of Man-day', dd.num_Field10 AS 'No. of Offshoring and PRC-T2 Man-day', dd.num_Field11 AS 'No. of Offshoring and PRC-T2 Man-day/Total No. of Man-day', dd.text_Field13 AS 'Description for Justification Offshore <25%', dd.num_Field12 AS 'Bid Bond (GAF)', dd.num_Field13 AS 'Bid Bond (GAF)(HKD)', dd.text_Field14 AS 'Contract without  Limited Liability (CWL)', dd.text_Field15 AS 'Cash flow mismatch noted (IGC)', dd.num_Field14 AS 'Total Bcase Cost', dd.num_Field15 AS 'Labor Cost', dd.num_Field16 AS 'Labor Cost %', dd.num_Field17 AS 'Travel Expenses', dd.num_Field18 AS 'Travel Expenses%', dd.num_Field19 AS 'Misc Expenses', dd.num_Field20 AS 'Misc Expenses %', dd.num_Field21 AS '3rd Party Expenses', dd.num_Field22 AS '3rd Party Expenses %', dd.num_Field23 AS 'TCV after VAT', dd.num_Field24 AS 'TCV after VAT(HKD)', dd.text_Field16 AS 'Temporary WO application', dd.text_Field17 AS 'Pre-sales Register', dd.text_Field18 AS 'CMT With Non Group Client Only', dd.text_Field19 AS 'DCI With Design & Build Only', dd.text_Field20 AS 'DC and/or IP Deals', dd.text_Field21 AS 'Approval Type', dd.text_Field22 AS 'Region', dd.text_Field23 AS 'Fast Track Approved'";
//        String str = "dd.text_Field01 AS 'Location', dd.text_Field02 AS 'Industry Client Partner', dd.text_Field03 AS 'Customer Name', dd.text_Field04 AS 'Project Description', dd.text_Field05 AS 'Industry', dd.text_Field06 AS 'Currency', dd.num_Field01 AS 'TCV', dd.num_Field02 AS 'TCV (HKD)', dd.date_Field01 AS 'Expected Contract Sign Date', dd.text_Field07 AS 'Account Manager', dd.text_Field08 AS 'Solution Manager', dd.text_Field09 AS 'Project Nature', dd.num_Field03 AS 'Total Direct Variable Cost', dd.num_Field04 AS 'Total Indirect Cost', dd.text_Field10 AS 'Year of New Sales Booked Revenue', dd.num_Field05 AS 'New Sales Booked Revenue', dd.num_Field06 AS 'EBITDA', dd.num_Field07 AS 'EBITDA Margin (in %) ', dd.text_Field11 AS 'Opportunity ID', dd.num_Field08 AS 'EBITDA Guideline', dd.num_Field09 AS 'Total No. of Man-day', dd.num_Field10 AS 'No. of Man-day Offshore', dd.num_Field11 AS 'No. of Man-day Offshore/Total No. of Man-day(in %)', dd.text_Field12 AS 'Justification for offshoring < 40%', dd.text_Field13 AS 'DC and/or IP Deals', dd.text_Field14 AS 'Pre-sales Register', dd.text_Field15 AS 'CMT With Non Group Client Only', dd.text_Field16 AS 'DCI With Design & Build Only', dd.text_Field17 AS 'Require CWL application & approval', dd.text_Field18 AS 'Cash flow mismatch noted (IGC)', dd.text_Field19 AS 'Approval Type', dd.text_Field20 AS 'Fast Track Approved', dd.text_Field21 AS 'End customer territory', dd.text_Field22 AS 'Led by', dd.num_Field12 AS 'EBIDTA Margin for Approval (in %)'";
//        String str = "dd.text_Field01 AS 'Location', dd.text_Field02 AS 'Industry Client Partner', dd.text_Field03 AS 'Customer Name', dd.text_Field04 AS 'Project Description', dd.text_Field05 AS 'Industry', dd.text_Field06 AS 'Currency', dd.num_Field01 AS 'TCV', dd.num_Field02 AS 'TCV (HKD)', dd.date_Field01 AS 'Expected Contract Sign Date', dd.text_Field07 AS 'Account Manager', dd.text_Field08 AS 'Solution Manager', dd.text_Field09 AS 'Project Nature', dd.num_Field03 AS 'Total Direct Variable Cost', dd.num_Field04 AS 'Total Indirect Cost', dd.text_Field10 AS 'Year of New Sales Booked Revenue', dd.num_Field05 AS 'New Sales Booked Revenue', dd.num_Field06 AS 'EBITDA : ', dd.num_Field07 AS 'EBIDTA Margin (in %) ', dd.text_Field11 AS 'Opportunity ID', dd.text_Field12 AS 'Contract without Limited Liability (CWL)', dd.text_Field13 AS 'Cash flow mismatch noted (IGC)'";
        String str = "dd.text_Field01 AS 'Location', dd.text_Field02 AS 'Industry Client Partner', dd.text_Field03 AS 'Customer Name', dd.text_Field04 AS 'Project Description', dd.text_Field05 AS 'Industry', dd.text_Field06 AS 'Currency', dd.num_Field01 AS 'TCV', dd.num_Field02 AS 'TCV (HKD)', dd.date_Field01 AS 'Expected Contract Sign Date', dd.text_Field07 AS 'Account Manager', dd.text_Field08 AS 'Solution Manager', dd.text_Field09 AS 'Project Nature', dd.num_Field03 AS 'Total Direct Variable Cost', dd.num_Field04 AS 'Total Indirect Cost', dd.text_Field10 AS 'Year of New Sales Booked Revenue', dd.num_Field05 AS 'New Sales Booked Revenue', dd.num_Field06 AS 'EBITDA', dd.num_Field07 AS 'EBITDA Margin (in %) ', dd.text_Field11 AS 'Opportunity ID', dd.num_Field08 AS 'EBITDA Guideline', dd.num_Field09 AS 'Total No. of Man-day', dd.num_Field10 AS 'No. of Man-day Offshore', dd.num_Field11 AS 'No. of Man-day Offshore/Total No. of Man-day(in %)', dd.text_Field12 AS 'Justification for offshoring < 40%', dd.text_Field13 AS 'DC and/or IP Deals', dd.text_Field14 AS 'Pre-sales Register', dd.text_Field15 AS 'CMT With Non Group Client Only', dd.text_Field16 AS 'DCI With Design & Build Only', dd.text_Field17 AS 'Require CWL application & approval', dd.text_Field18 AS 'Cash flow mismatch noted (IGC)', dd.text_Field19 AS 'Approval Type', dd.text_Field20 AS 'Fast Track Approved', dd.text_Field21 AS 'End customer territory', dd.text_Field22 AS 'Led by', dd.num_Field12 AS 'EBIDTA Margin for Approval (in %)'";
        char[] chars = str.toCharArray();
        for (int i = 0; i < chars.length; i++) {
            System.out.print(chars[i]);
            if (chars[i] == ',') {
                System.out.println("");
            }
        }
    }
}
