server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    username: edms
    password: edms
    url: jdbc:mysql://localhost:3306/marks?useUnicode=true&amp&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      db-type: mysql
      table-prefix: t_
      column-underline: true
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.marks.edms.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl