server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    username: edms
    password: edms
    url: jdbc:mysql://localhost:3306/newbee_mall_db?useUnicode=true&amp&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  web:
    resources:
      static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml

#  %d{HH:mm:ss.SSS}——日志输出时间
#  %thread——输出日志的进程名字，这在Web应用以及异步任务处理中很有用
#  %-5level——日志级别，并且使用5个字符靠左对齐
#  %logger- ——日志输出者的名字
#  %msg——日志消息
#  %n——平台的换行符

#logging:
#  config: classpath:/logback/logback-spring.xml
#  path: C:\logs\gitProject
#  file: new_bee_mall.log
#  pattern:
#    file: %d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n
#    console: %d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n